// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DeCasteljau_cpp
Rcpp::NumericMatrix DeCasteljau_cpp(Rcpp::List rsegments, Rcpp::NumericVector keyTimes, Rcpp::NumericVector times);
RcppExport SEXP _qsplines_DeCasteljau_cpp(SEXP rsegmentsSEXP, SEXP keyTimesSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type rsegments(rsegmentsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type keyTimes(keyTimesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(DeCasteljau_cpp(rsegments, keyTimes, times));
    return rcpp_result_gen;
END_RCPP
}
// cpp_calculate_control_quaternions
Rcpp::NumericMatrix cpp_calculate_control_quaternions(Rcpp::NumericMatrix Rquaternions, Rcpp::NumericVector times, double t, double c, double b);
RcppExport SEXP _qsplines_cpp_calculate_control_quaternions(SEXP RquaternionsSEXP, SEXP timesSEXP, SEXP tSEXP, SEXP cSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Rquaternions(RquaternionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_calculate_control_quaternions(Rquaternions, times, t, c, b));
    return rcpp_result_gen;
END_RCPP
}
// control_points_cpp
Rcpp::NumericMatrix control_points_cpp(Rcpp::NumericVector keyTimesR, Rcpp::NumericMatrix keyRotorsR, bool closed, double t, double c, double b);
RcppExport SEXP _qsplines_control_points_cpp(SEXP keyTimesRSEXP, SEXP keyRotorsRSEXP, SEXP closedSEXP, SEXP tSEXP, SEXP cSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type keyTimesR(keyTimesRSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type keyRotorsR(keyRotorsRSEXP);
    Rcpp::traits::input_parameter< bool >::type closed(closedSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(control_points_cpp(keyTimesR, keyRotorsR, closed, t, c, b));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qsplines_DeCasteljau_cpp", (DL_FUNC) &_qsplines_DeCasteljau_cpp, 3},
    {"_qsplines_cpp_calculate_control_quaternions", (DL_FUNC) &_qsplines_cpp_calculate_control_quaternions, 5},
    {"_qsplines_control_points_cpp", (DL_FUNC) &_qsplines_control_points_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_qsplines(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
