# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DeCasteljau_cpp <- function(rsegments, keyTimes, times) {
    .Call(`_qsplines_DeCasteljau_cpp`, rsegments, keyTimes, times)
}

cpp_calculate_control_quaternions <- function(Rquaternions, times, t, c, b) {
    .Call(`_qsplines_cpp_calculate_control_quaternions`, Rquaternions, times, t, c, b)
}

control_points_cpp <- function(keyTimesR, keyRotorsR, closed, t, c, b) {
    .Call(`_qsplines_control_points_cpp`, keyTimesR, keyRotorsR, closed, t, c, b)
}

